### PR TITLE
:broom: Removing the vendor dir :fireworks:

### PR DESCRIPTION
**Pull request by cardil**
# Changes

- :broom: Removing the vendor dir :fireworks:

/kind cleanup

Tests knative/hack#311
Tests knative/hack#222

### CODE REVIEW

**Comment by cardil** [comment]
The failure https://github.com/knative-extensions/kn-plugin-event/actions/runs/6089754374/job/16523241031?pr=307 is expected, as in order to use https://github.com/knative/hack/pull/222 and https://github.com/knative/hack/pull/311 I needed to use the `replace` stanza in `go.mod` which is reported by the linter.

**Comment by cardil** [comment]
/unhold

The Func's PR was already merged: https://github.com/knative/func/pull/1966

/cc @dsimansk 
/cc @rhuss

**Comment by rhuss** [comment]
Well, I think this is fine. I can't dive into the PR itself, and not sure what other side-effects will happen when we inline the plugin into `kn`, which still uses the vendor dir. If you are sure that this doesn't harm (i.e. still works), happy to merge this (so feel free to unhold then)

/approve
/lgtm
/hold

**Comment by cardil** [comment]
> @rhuss Well, I think this is fine. I can't dive into the PR itself, and not sure what other side-effects will happen when we inline the plugin into `kn`, which still uses the vendor dir. If you are sure that this doesn't harm (i.e. still works), happy to merge this (so feel free to unhold then)

Vendorless applies only to upstream projects. The vendors like RH will probably continue to vendor deps on their products, just to have a way to apply patches if needed.

Also, vendorless project doesn't change anything when the plugin is being embedded into other, like in kn.

See the epic for more info: https://github.com/knative/infra/issues/134

/unhold

**Pull request merged**
